-- Write your migration SQL up here

CREATE TYPE recipe_stage AS ENUM (
  'preparation',
  'mash',
  'sparge',
  'boil',
  'whirlpool',
  'fermentation',
  'conditioning',
  'packaging'
);

CREATE TABLE recipes(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL
   REFERENCES organizations(id)
   ON DELETE CASCADE,
  name TEXT NOT NULL COLLATE "identifier",
  description TEXT NOT NULL DEFAULT '',
  
  -- Brewing Metrics
  batch_size DECIMAL(20, 6) NOT NULL DEFAULT 20.0,
  batch_size_unit unit NOT NULL DEFAULT 'liter',
  batch_size_normalized DECIMAL(20, 6) NOT NULL
    GENERATED ALWAYS AS (
      to_canonical_qty(batch_size, batch_size_unit)
    ) STORED,

  target_og DECIMAL(6, 3) NOT NULL DEFAULT 1.000,
  target_fg DECIMAL(6, 3) NOT NULL DEFAULT 1.000,
  target_abv DECIMAL(4, 2) NOT NULL DEFAULT 0.0,
  target_ibu INT NOT NULL DEFAULT 0,
  target_srm DECIMAL(5, 2) NOT NULL DEFAULT 0.0,
  boil_time_minutes INT NOT NULL DEFAULT 60,
  target_efficiency DECIMAL(5, 2) NOT NULL DEFAULT 75.0,

  published_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT recipes_have_unique_name_per_org
    UNIQUE (organization_id, name),
  
  CONSTRAINT batch_size_must_be_volumetric
    CHECK (to_unit_category(batch_size_unit) = 'volume')
);

CREATE TABLE recipe_ingredients(
  recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES items(id),
  amount DECIMAL(20, 6) NOT NULL,
  amount_unit unit NOT NULL,
  amount_unit_category unit_category NOT NULL
    GENERATED ALWAYS AS (
      to_unit_category(amount_unit)
    )
    STORED,
  amount_normalized DECIMAL(20, 6) NOT NULL
    GENERATED ALWAYS AS (
      to_canonical_qty(amount, amount_unit)
    ) STORED,
  
  -- Timing and Stage
  addition_stage recipe_stage NOT NULL DEFAULT 'boil',
  addition_time_minutes INT, -- (e.g. 60 for boil, 7 days for dry hop)
  
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (recipe_id, item_id)
);

CREATE TABLE recipe_steps(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  step_number INT NOT NULL,
  step_stage recipe_stage NOT NULL DEFAULT 'mash',
  step_description TEXT NOT NULL DEFAULT '',
  
  -- Functional step data
  duration_minutes INT,
  temperature_celsius DECIMAL(5, 2),
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
