{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE NoFieldSelectors #-}

module Noided.Web.Internal.Type.SignedMessage
  ( Signer,
    signerHMACSHA512,

    -- * Messages to sign
    SignableMessage (..),

    -- * Signing messages
    signSignableMessage,
    signMessageExpPurpose,
    signMessagePurpose,

    -- * Result of signed messages
    SignedValue (getSignedValue),
    verifyMessage,
  )
where

import Control.Monad
import Crypto.Hash.SHA512 qualified as SHA512
import Data.Aeson
import Data.Bifunctor
import Data.ByteArray qualified as BA
import Data.ByteString
import Data.ByteString.Base64.URL qualified as B64
import Data.ByteString.Lazy qualified as LBS
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TEnc
import Data.Time
import GHC.Generics

-- | A value that we know was signed.
newtype SignedValue a = UnsafeMkSignedValue {getSignedValue :: a}
  deriving (Show, Eq, Ord)

data SignableMessage a
  = SignableMessage
  { -- | The actual value to sign
    val :: a,
    -- | The time at which this value expires
    exp :: Maybe UTCTime,
    -- | The scope of the value, used to separate purposes of signed values
    scope :: Maybe Text
  }
  deriving (Show, Read, Eq, Ord, Generic)

instance (ToJSON a) => ToJSON (SignableMessage a) where
  toEncoding = genericToEncoding (defaultOptions {omitNothingFields = True})
  toJSON = genericToJSON (defaultOptions {omitNothingFields = True})

instance (FromJSON a) => FromJSON (SignableMessage a) where
  parseJSON = genericParseJSON (defaultOptions {omitNothingFields = True})

signMessageExpPurpose :: (ToJSON a) => Signer -> UTCTime -> Text -> a -> Text
signMessageExpPurpose signer exp' purpose msg =
  signSignableMessage signer $ SignableMessage {val = msg, exp = Just exp', scope = Just purpose}

signMessagePurpose :: (ToJSON a) => Signer -> Text -> a -> Text
signMessagePurpose signer purpose msg =
  signSignableMessage signer $ SignableMessage {val = msg, exp = Nothing, scope = Just purpose}

-- | Sign some signable message.
signSignableMessage :: (ToJSON a) => Signer -> SignableMessage a -> Text
signSignableMessage signer msg =
  TEnc.decodeUtf8Lenient messageJSONB64
    <> splitter
    <> TEnc.decodeUtf8Lenient signatureB64
  where
    messageJSONText = LBS.toStrict (encode msg)
    messageJSONB64 = B64.encode messageJSONText
    signatureBytes = signer.signatureFor messageJSONB64
    signatureB64 = B64.encode signatureBytes

-- | Verify a message previous generated by signing some value.
verifyMessage ::
  (FromJSON a) =>
  -- | Signer to use for verification
  Signer ->
  -- | Current time
  UTCTime ->
  -- | Purpose of the signature.
  Maybe Text ->
  -- | Signed message value
  Text ->
  -- | Either the signed value or a decoding error
  Either SignedMessageFailure (SignedValue a)
verifyMessage signer currentTime purpose message = do
  bs <- verifyMessageBytes signer message
  json <- parseMsgJSON bs
  verifySigned currentTime purpose json

verifySigned :: UTCTime -> Maybe Text -> SignableMessage a -> Either SignedMessageFailure (SignedValue a)
verifySigned currT purpose msg = do
  case msg.exp of
    Nothing -> Right ()
    Just t
      | t < currT -> Left MessageExpired
      | otherwise -> Right ()
  unless (msg.scope == purpose) $ Left PurposeDidNotMatch
  return $ UnsafeMkSignedValue msg.val

-- | Why a signed message failed.
data SignedMessageFailure
  = MessageTooShort
  | SplitterNotFound
  | SignatureNotBase64 String
  | SignatureDidNotMatch
  | MessageNotBase64 String
  | MessageNotJSON String
  | PurposeDidNotMatch
  | MessageExpired
  deriving (Show, Read, Eq, Ord, Generic)
  deriving (ToJSON, FromJSON) via (Generically SignedMessageFailure)

splitter :: Text
splitter = "."

parseMsgJSON :: (FromJSON a) => ByteString -> Either SignedMessageFailure (SignableMessage a)
parseMsgJSON = first MessageNotJSON . eitherDecodeStrict

verifyMessageBytes :: Signer -> Text -> Either SignedMessageFailure ByteString
verifyMessageBytes signer msg = do
  (base64Msg, signatureBytes) <- splitSignatureBytes signer msg
  let msgBytes = TEnc.encodeUtf8 base64Msg
  unless (signer.verifySignature signatureBytes msgBytes) $
    Left SignatureDidNotMatch
  first MessageNotBase64 $
    B64.decodePadded msgBytes

splitSignatureBytes :: Signer -> Text -> Either SignedMessageFailure (Text, ByteString)
splitSignatureBytes _signer msg = do
  let (payloadWithSplitter, signature) = Text.breakOnEnd splitter msg
  when (Text.null payloadWithSplitter) $ Left SplitterNotFound
  let payload = Text.dropEnd 1 payloadWithSplitter
  let signatureBytes = B64.decodeLenient $ TEnc.encodeUtf8 signature
  return (payload, signatureBytes)

data Signer
  = MkSigner
  { signatureFor :: !(ByteString -> ByteString),
    verifySignature :: !(ByteString -> ByteString -> Bool)
  }

signerHMACSHA512 :: ByteString -> Signer
signerHMACSHA512 key = MkSigner {..}
  where
    signatureFor = SHA512.hmac key
    verifySignature sig val =
      let computed = SHA512.hmac key val
       in BA.constEq sig computed
