name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: optimize_beer_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ghc: ['9.6.7', '9.8.2']
        cabal: ['3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Load database schema
      run: |
        docker exec -i ${{ job.services.postgres.id }} env PGPASSWORD=password psql -U postgres -d optimize_beer_test < optimize-beer/db/schema.sql

    - name: Configure
      run: cabal configure --enable-tests
    - name: Dry run
      run: cabal build all --dry-run
    - name: Restore Cached Dependencies
      uses: actions/cache/restore@v4
      id: restore-deps-cache
      env:
        cache-name: cache-cabal
      with:
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Install dependencies
      run: |
        cabal build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Save dependencies cache
      uses: actions/cache/save@v4
      with:
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
        key: ${{ steps.restore-deps-cache.outputs.cache-primary-key }}
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:password@localhost:5432/optimize_beer_test
      run: cabal test all
